version: "3.2"

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - 8080:80
    entrypoint: sh -c "sleep 3 && php /var/www/html/artisan migrate --force && apache2-foreground"
  db:
    image: mysql
    ports: 
      - "3306:3306" # Expose ports for manual inspection
    environment:
      - MYSQL_ROOT_PASSWORD=laravel1